const state={route:location.hash.slice(1)||'home',previousRoute:'home',query:'',favourites:JSON.parse(localStorage.getItem('templemap-favourites')||'[]'),textSize:localStorage.getItem('templemap-text-size')||'small',homeData:null,templeUpdates:null};

const temples=[
{id:'ochira',name:'Oachira Parabrahma Temple',ml:'ഓച്ചിറ പരബ്രഹ്മ ക്ഷേത്രം',place:'Oachira',district:'Kollam',state:'Kerala',focus:'Parabrahmam',type:'Pilgrimage Centre',tradition:'Non-idol worship'},
{id:'kottakkal-vishwambhara',name:'Kottakkal Vishwambhara Temple',ml:'കോട്ടക്കൽ വിശ്വംഭര ക്ഷേത്രം',place:'Kottakkal',district:'Malappuram',state:'Kerala',focus:'Shiva',type:'Temple',tradition:'Hinduism'},
{id:'somnath',name:'Somnath Temple',ml:'സോമനാഥ ക്ഷേത്രം',place:'Prabhas Patan',district:'Gir Somnath',state:'Gujarat',focus:'Shiva',type:'Temple',tradition:'Hinduism'},
{id:'vaishno-devi',name:'Shri Mata Vaishno Devi Shrine',ml:'ശ്രീ മാതാ വൈഷ്ണോ ദേവി ക്ഷേത്രം',place:'Katra',district:'Reasi',state:'Jammu and Kashmir',focus:'Vaishno Devi',type:'Shrine',tradition:'Hinduism'},
{id:'tirumala',name:'Tirumala Venkateswara Temple',ml:'തിരുമല വെങ്കടേശ്വര ക്ഷേത്രം',place:'Tirumala',district:'Tirupati',state:'Andhra Pradesh',focus:'Venkateswara',type:'Temple',tradition:'Vaishnavism'},
{id:'sabarimala',name:'Sabarimala Sree Dharma Sastha Temple',ml:'ശബരിമല ശ്രീ ധർമ്മശാസ്താ ക്ഷേത്രം',place:'Sabarimala',district:'Pathanamthitta',state:'Kerala',focus:'Ayyappa',type:'Temple',tradition:'Hinduism'},
{id:'guruvayur',name:'Guruvayur Sree Krishna Temple',ml:'ഗുരുവായൂർ ശ്രീകൃഷ്ണ ക്ഷേത്രം',place:'Guruvayur',district:'Thrissur',state:'Kerala',focus:'Krishna',type:'Temple',tradition:'Vaishnavism'},
{id:'kashi-vishwanath',name:'Kashi Vishwanath Temple',ml:'കാശി വിശ്വനാഥ ക്ഷേത്രം',place:'Varanasi',district:'Varanasi',state:'Uttar Pradesh',focus:'Shiva',type:'Temple',tradition:'Hinduism'},
{id:'vadakkumnathan',name:'Vadakkumnathan Temple',ml:'വടക്കുന്നാഥൻ ക്ഷേത്രം',place:'Thrissur',district:'Thrissur',state:'Kerala',focus:'Shiva',type:'Temple',tradition:'Hinduism'}
];

const states=['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','Andaman and Nicobar Islands','Chandigarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry'];
const browseData={
'State / Union Territory':states,
'Religion':['Hinduism','Buddhism','Jainism','Sikhism','Islam','Christianity','Other / Syncretic'],
'Sect / Tradition':['Vaishnavism','Shaivism','Shaktism','Smartism','Ayyappa tradition','Non-idol worship','Buddhist traditions','Jain traditions','Sikh traditions','Local / Folk tradition','Tribal tradition','Mixed / Multiple traditions'],
'Deity / Sacred Focus':['Shiva','Vishnu','Krishna','Rama','Venkateswara','Ayyappa','Durga','Kali','Lakshmi','Ganesha','Murugan','Hanuman','Devi / Shakti','Vaishno Devi','Surya','Parabrahmam','Buddha','Mahavira','Guru / Saint','Sacred symbol','Nature / Sacred grove','Multiple deities','No specific deity','Unknown'],
'Site Category':['Temple','Shrine','Pilgrimage Centre','Ashram','Matha / Mutt','Monastery','Gurudwara','Jain Temple','Cave Shrine','Sacred Grove','Sacred Tank','Memorial / Samadhi','Heritage Temple','Temple Complex','Other Sacred Place'],
'Heritage':['UNESCO World Heritage','ASI Protected','State Protected','Heritage Structure','Living Heritage','Archaeological Site','Not Yet Classified'],
'Historical Figure':['Adi Shankaracharya','Ramanujacharya','Chaitanya Mahaprabhu','Madhvacharya','Basavanna','Guru Nanak','Mahavira','Buddha','Local ruler / dynasty','Saint / Spiritual teacher','Historical figure','None recorded'],
'Architecture':['Dravidian','Nagara','Vesara','Kerala Traditional','Himalayan','Kalinga','Hoysala','Mughal-era influence','Buddhist','Jain','Indo-Islamic','Regional / Vernacular','Modern','Mixed / Multiple'],
'Pilgrimage / Temple Circuits':['Char Dham','Jyotirlinga','Shakti Peetha','Divya Desam','Pancha Bhoota','Kumbh Mela','12 Jyotirlingas','108 Divya Desams','Ayyappa pilgrimage','Navadurga','Regional circuit'],
'Festival / Event':['Onam','Navaratri','Karthika Deepam','Maha Shivaratri','Janmashtami','Rama Navami','Vijayadashami','Deepavali','Kumbh Mela','Thrissur Pooram','Temple annual festival','Other festival']
};

const normalize=s=>String(s??'').normalize('NFKC').toLocaleLowerCase().replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[\s\-–—'’.`]/g,'');
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const navigate=r=>{location.hash=r};
function applyText(){document.body.dataset.textSize=state.textSize;}
function searchTemples(q){const n=normalize(q);if(!n)return[];return temples.filter(t=>[t.name,t.ml,t.place,t.district,t.state,t.focus,t.type,t.tradition].some(v=>normalize(v).includes(n)));}
function didYouMean(q){const n=normalize(q);if(!n)return'';const hit=temples.find(t=>normalize(t.name).startsWith(n.slice(0,Math.max(2,n.length-1)))||normalize(t.ml).startsWith(n.slice(0,Math.max(2,n.length-1))));return hit&&!searchTemples(q).length?`<p class="suggestion">Did you mean <button class="link-button" data-suggest="${escapeHtml(hit.name)}">${escapeHtml(hit.name)}</button>?</p>`:'';}
function searchBar(id,value=''){return `<div class="search-box"><input id="${id}" value="${escapeHtml(value)}" placeholder="Search in English or Malayalam" autocomplete="off" enterkeyhint="search"><button class="search-go" id="${id}Go" aria-label="Search">⌕</button></div>`;}
function pageHead(title,back='home'){return `<div class="page-head"><a class="back" href="#${escapeHtml(back)}">← Back</a><h1>${escapeHtml(title)}</h1></div>`;}
function resultLink(t){return `<a class="result-link" href="#temple/${t.id}"><div class="result-thumb" aria-hidden="true"></div><div class="result-main"><strong>${escapeHtml(t.name)}</strong><span>${escapeHtml(t.place)}, ${escapeHtml(t.district)}, ${escapeHtml(t.state)}</span><small>✦ ${escapeHtml(t.focus)} · ${escapeHtml(t.type)}</small></div><b class="result-arrow">›</b></a>`;}
function connectivity(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;let label='Live',cls='';if(!navigator.onLine){label='No Data';cls='no-data';}else if(c&&['slow-2g','2g'].includes(c.effectiveType)){label='Weak Data';cls='weak-data';}return `<span class="connectivity ${cls}"><i></i>${label}</span>`;}
function homePage(){const h=state.homeData||{},ids=h.featuredTempleIds||['ochira','kottakkal-vishwambhara','somnath','tirumala'],featured=ids.map(id=>temples.find(t=>t.id===id)).filter(Boolean),news=(h.newsLinks||[]).map(x=>`<a class="news-link" href="${escapeHtml(x.url)}" target="_blank" rel="noopener"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.source||'Original source')}</small></a>`).join('');return `<section class="hero"><div><div class="eyebrow">EXPLORE · DISCOVER · CONNECT</div><h1>India’s Sacred Places</h1><p>${escapeHtml(h.description||'A lightweight directory of temples and sacred places across India.')}</p></div></section>${connectivity()}${searchBar('homeSearch')}<div class="actions"><button class="primary" id="homeSearchButton">⌕ Search Temples</button><a class="secondary" href="#browse">☷ Browse</a></div><section class="section"><h2>Featured Temples</h2><div class="feature-strip">${featured.map(t=>`<a class="feature" href="#temple/${t.id}"><div class="feature-thumb"></div><strong>${escapeHtml(t.name)}</strong><small>${escapeHtml(t.place)}</small></a>`).join('')}</div></section><section class="section"><h2>Latest Temple News & Festivals</h2>${news?`<div class="news-list">${news}</div>`:'<div class="card"><strong>Updates will appear here</strong><small>Official and verified current links can be added through the data files.</small></div>'}</section>`;}
function searchPage(){const r=searchTemples(state.query);return `${pageHead('Search Temples')}${searchBar('searchInput',state.query)}${state.query?`<span class="count-pill">${r.length.toLocaleString()} results found</span>${didYouMean(state.query)}${r.length?`<div class="result-list search-page-list">${r.map(resultLink).join('')}</div>`:'<div class="empty">No matching temples found.</div>'}`:'<p class="muted">Search by temple name, Malayalam name, place, district, state or sacred focus.</p>'}`;}
function browsePage(){return `${pageHead('Browse Temples')}<p class="muted browse-help">Choose a category. Each menu contains the complete option set.</p><div class="browse-grid">${Object.entries(browseData).map(([name,options])=>`<label class="browse-row"><span><strong>${escapeHtml(name)}</strong><small>${options.length} options</small></span><select data-browse="${escapeHtml(name)}"><option value="">Select</option>${options.map(o=>`<option value="${escapeHtml(o)}">${escapeHtml(o)}</option>`).join('')}</select></label>`).join('')}</div>`;}
function favouritesPage(){const saved=temples.filter(t=>state.favourites.includes(t.id));return `${pageHead('Favourites')}${saved.length?`<div class="result-list favourite-list">${saved.map(resultLink).join('')}</div>`:'<div class="empty">No favourites saved yet.<br>Open a temple and choose “Add to Favourites”.</div>'}`;}
function templePage(id){const t=temples.find(x=>x.id===id);if(!t)return'<div class="empty">Temple not found.</div>';const saved=state.favourites.includes(id),u=state.templeUpdates?.temples?.[id]||{},links=(u.links||[]).map(x=>`<a class="secondary" href="${escapeHtml(x.url)}" target="_blank" rel="noopener">${escapeHtml(x.label)}</a>`).join(''),news=(u.newsLinks||[]).map(x=>`<a class="news-link" href="${escapeHtml(x.url)}" target="_blank" rel="noopener"><strong>${escapeHtml(x.title)}</strong><small>${escapeHtml(x.source||'Original source')}</small></a>`).join('');return `${pageHead('Temple',state.previousRoute||'search')}<div class="detail-grid"><div class="detail-image"></div><div class="detail-panel detail-scroll"><div class="temple-title"><div><h2>${escapeHtml(t.name)}</h2><p class="muted">${escapeHtml(t.ml)}</p></div><button class="icon-small" id="favButton" aria-label="Favourite">${saved?'♥':'♡'}</button></div><p class="place-line">📍 ${escapeHtml(t.place)}, ${escapeHtml(t.district)}, ${escapeHtml(t.state)}</p><div class="field"><b>Sacred Focus</b><span>${escapeHtml(t.focus)}</span></div><div class="field"><b>Site Category</b><span>${escapeHtml(t.type)}</span></div><div class="field"><b>Tradition</b><span>${escapeHtml(t.tradition)}</span></div><div class="actions compact"><button class="${saved?'secondary':'primary'}" id="favText">${saved?'♥ Saved':'♡ Add to Favourites'}</button><button class="secondary" id="shareTemple">↗ Share</button></div>${links?`<section class="section"><h3>Official Temple Links</h3><div class="actions">${links}</div></section>`:''}${news?`<section class="section"><h3>Latest News & Festivals</h3><div class="news-list">${news}</div></section>`:'<section class="section"><h3>Nearby Temples</h3><p class="muted">Nearby temples will appear when the India-wide location index is connected.</p></section>'}<div class="notice">TempleMap India is an independent public information resource. Verify changing information with the original authority before travelling.${u.lastVerified?` Last verified: ${escapeHtml(u.lastVerified)}.`:''}</div></div></div>`;}
function settingsPage(){return `${pageHead('Settings')}<div class="settings-list"><div class="card setting-row"><div><strong>📍 Location</strong><small id="locationState">Enable location for nearby-temple features.</small></div><button class="secondary" id="locationButton">Enable</button></div><div class="card setting-row"><div><strong>AA · Text Size</strong><small>Small is the default. Changing size only changes text, not the layout.</small></div><select id="textSize"><option value="small" ${state.textSize==='small'?'selected':''}>Small</option><option value="normal" ${state.textSize==='normal'?'selected':''}>Normal</option><option value="large" ${state.textSize==='large'?'selected':''}>Large</option><option value="xlarge" ${state.textSize==='xlarge'?'selected':''}>Extra Large</option></select></div><div class="card"><strong>Share TempleMap India</strong><small>Share this independent public resource.</small><div class="actions compact"><button class="secondary" id="shareApp">↗ Share</button></div></div><div class="card"><strong>About</strong><small>TempleMap India is an independent public information directory, not a government website or government service.</small></div><div class="card"><strong>Privacy</strong><small>Favourites and text-size preference are stored locally in this browser.</small></div></div>`;}
function render(){const app=document.getElementById('app'),[base,id]=state.route.split('/');if(base==='search')app.innerHTML=searchPage();else if(base==='browse')app.innerHTML=browsePage();else if(base==='favourites')app.innerHTML=favouritesPage();else if(base==='temple')app.innerHTML=templePage(id);else if(base==='settings')app.innerHTML=settingsPage();else app.innerHTML=homePage();app.classList.toggle('tab-fixed',base==='home'||base==='browse'||base==='settings'||base==='temple');const settings=document.getElementById('settingsButton');if(settings)settings.hidden=base!=='home';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===base||(base==='temple'&&state.previousRoute.split('/')[0]===a.dataset.nav)));applyText();bindEvents();}
function runSearch(id){const el=document.getElementById(id);if(!el)return;state.query=el.value.trim();navigate('search');}
function bindEvents(){document.getElementById('homeSearchButton')?.addEventListener('click',()=>runSearch('homeSearch'));document.getElementById('homeSearchGo')?.addEventListener('click',()=>runSearch('homeSearch'));document.getElementById('searchInputGo')?.addEventListener('click',()=>runSearch('searchInput'));['homeSearch','searchInput'].forEach(id=>document.getElementById(id)?.addEventListener('keydown',e=>{if(e.key==='Enter')runSearch(id)}));document.querySelectorAll('[data-suggest]').forEach(b=>b.addEventListener('click',()=>{state.query=b.dataset.suggest;render()}));document.querySelectorAll('[data-browse]').forEach(s=>s.addEventListener('change',e=>{if(e.target.value){state.query=e.target.value;navigate('search')}}));document.getElementById('settingsButton')?.addEventListener('click',()=>navigate('settings'));document.getElementById('favButton')?.addEventListener('click',toggleFavourite);document.getElementById('favText')?.addEventListener('click',toggleFavourite);document.getElementById('shareTemple')?.addEventListener('click',shareCurrent);document.getElementById('shareApp')?.addEventListener('click',shareApp);document.getElementById('locationButton')?.addEventListener('click',enableLocation);document.getElementById('textSize')?.addEventListener('change',e=>{state.textSize=e.target.value;localStorage.setItem('templemap-text-size',state.textSize);applyText();});}
function toggleFavourite(){const id=state.route.split('/')[1];state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];localStorage.setItem('templemap-favourites',JSON.stringify(state.favourites));render();}
async function shareApp(){const data={title:'TempleMap India',text:'Explore India’s sacred places.',url:location.href};if(navigator.share)try{await navigator.share(data)}catch(e){}else if(navigator.clipboard)await navigator.clipboard.writeText(location.href);}
async function shareCurrent(){const title=document.querySelector('.temple-title h2')?.textContent||'TempleMap India';const data={title,text:`Explore ${title} on TempleMap India.`,url:location.href};if(navigator.share)try{await navigator.share(data)}catch(e){}else if(navigator.clipboard)await navigator.clipboard.writeText(location.href);}
function enableLocation(){const out=document.getElementById('locationState');if(!navigator.geolocation){out.textContent='Location is not supported by this browser.';return}navigator.geolocation.getCurrentPosition(()=>out.textContent='Location access is enabled on this device.',()=>out.textContent='Location permission was not granted.');}
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1)||'home';if(next.startsWith('temple/'))state.previousRoute=state.route;state.route=next;render();});
(async()=>{try{state.homeData=await fetch('data/home-data.json?rev=4',{cache:'no-store'}).then(r=>r.ok?r.json():null);state.templeUpdates=await fetch('data/temple-updates.json?rev=4',{cache:'no-store'}).then(r=>r.ok?r.json():null);}catch(e){}render();})();