const state={route:location.hash.slice(1)||'home',previousRoute:'home',query:'',favourites:JSON.parse(localStorage.getItem('templemap-favourites')||'[]'),textSize:localStorage.getItem('templemap-text-size')||'small',sort:'relevance',location:null,filters:{},homeData:null,templeUpdates:null};
const temples=[
{id:'ochira',name:'Oachira Parabrahma Temple',ml:'ഓച്ചിറ പരബ്രഹ്മ ക്ഷേത്രം',place:'Oachira',district:'Kollam',state:'Kerala',focus:'Parabrahmam',type:'Pilgrimage Centre',tradition:'Non-idol worship',lat:9,lng:76.55},
{id:'kottakkal-vishwambhara',name:'Kottakkal Vishwambhara Temple',ml:'കോട്ടക്കൽ വിശ്വംഭര ക്ഷേത്രം',place:'Kottakkal',district:'Malappuram',state:'Kerala',focus:'Shiva',type:'Temple',tradition:'Hinduism',lat:11,lng:75.99},
{id:'somnath',name:'Somnath Temple',ml:'സോമനാഥ ക്ഷേത്രം',place:'Prabhas Patan',district:'Gir Somnath',state:'Gujarat',focus:'Shiva',type:'Temple',tradition:'Hinduism',lat:20.89,lng:70.4},
{id:'vaishno-devi',name:'Shri Mata Vaishno Devi Shrine',ml:'ശ്രീ മാതാ വൈഷ്ണോ ദേവി ക്ഷേത്രം',place:'Katra',district:'Reasi',state:'Jammu and Kashmir',focus:'Vaishno Devi',type:'Shrine',tradition:'Hinduism',lat:33.03,lng:74.95},
{id:'tirumala',name:'Tirumala Venkateswara Temple',ml:'തിരുമല വെങ്കടേശ്വര ക്ഷേത്രം',place:'Tirumala',district:'Tirupati',state:'Andhra Pradesh',focus:'Venkateswara',type:'Temple',tradition:'Vaishnavism',lat:13.68,lng:79.35},
{id:'sabarimala',name:'Sabarimala Sree Dharma Sastha Temple',ml:'ശബരിമല ശ്രീ ധർമ്മശാസ്താ ക്ഷേത്രം',place:'Sabarimala',district:'Pathanamthitta',state:'Kerala',focus:'Ayyappa',type:'Temple',tradition:'Hinduism',lat:9.43,lng:77.08},
{id:'guruvayur',name:'Guruvayur Sree Krishna Temple',ml:'ഗുരുവായൂർ ശ്രീകൃഷ്ണ ക്ഷേത്രം',place:'Guruvayur',district:'Thrissur',state:'Kerala',focus:'Krishna',type:'Temple',tradition:'Vaishnavism',lat:10.59,lng:76.04},
{id:'kashi-vishwanath',name:'Kashi Vishwanath Temple',ml:'കാശി വിശ്വനാഥ ക്ഷേത്രം',place:'Varanasi',district:'Varanasi',state:'Uttar Pradesh',focus:'Shiva',type:'Temple',tradition:'Hinduism',lat:25.31,lng:83.01},
{id:'vadakkumnathan',name:'Vadakkumnathan Temple',ml:'വടക്കുന്നാഥൻ ക്ഷേത്രം',place:'Thrissur',district:'Thrissur',state:'Kerala',focus:'Shiva',type:'Temple',tradition:'Hinduism',lat:10.52,lng:76.21}];
const states=['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','Andaman and Nicobar Islands','Chandigarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry'];
const browseData={'State / Union Territory':states,'District':[],'Village / Town / City':[],'Religion':['Hinduism','Buddhism','Jainism','Sikhism','Other Indian tradition'],'Sect / Tradition':['Vaishnavism','Shaivism','Shaktism','Smartism','Ayyappa tradition','Non-idol worship','Buddhist traditions','Jain traditions','Sikh traditions','Local / Folk tradition','Tribal tradition','Mixed / Multiple traditions'],'Sacred Focus':['Shiva','Vishnu','Krishna','Rama','Devi / Shakti','Lakshmi','Ganesha','Murugan / Kartikeya','Ayyappa / Sastha','Surya','Hanuman','Other named deity','Multiple / Composite','Formless divine principle','Sacred person / saint','Nature / sacred grove','Sacred symbol / object','Ancestor / ancestral tradition','No specific deity','Unknown'],'Site Category':['Temple','Shrine','Pilgrimage Centre','Ashram','Matha / Mutt','Monastery','Gurudwara','Jain Temple','Cave Shrine','Sacred Grove','Sacred Tank','Memorial / Samadhi','Heritage Temple','Temple Complex','Other Sacred Place'],'Heritage':['UNESCO World Heritage','ASI Protected','State Protected','Heritage Structure','Living Heritage','Archaeological Site','Not Yet Classified'],'Historical Figure':['Adi Shankaracharya','Ramanujacharya','Chaitanya Mahaprabhu','Madhvacharya','Basavanna','Guru Nanak','Mahavira','Buddha','Local ruler / dynasty','Saint / Spiritual teacher','Historical figure','None recorded'],'Architecture':['Dravidian','Nagara','Vesara','Kerala Traditional','Himalayan','Kalinga','Hoysala','Mughal-era influence','Buddhist','Jain','Indo-Islamic','Regional / Vernacular','Modern','Mixed / Multiple'],'Pilgrimage / Temple Circuits':['Char Dham','Jyotirlinga','Shakti Peetha','Divya Desam','Pancha Bhoota','Kumbh Mela','12 Jyotirlingas','108 Divya Desams','Ayyappa pilgrimage','Navadurga','Regional circuit'],'Festival / Event':['Onam','Navaratri','Karthika Deepam','Maha Shivaratri','Janmashtami','Rama Navami','Vijayadashami','Deepavali','Kumbh Mela','Thrissur Pooram','Temple annual festival','Other festival']};
temples.forEach(t=>{t.religion=t.religion||'Hinduism';t.sacredFocus=t.sacredFocus||({Parabrahmam:'Formless divine principle',Shiva:'Shiva',Krishna:'Krishna',Venkateswara:'Vishnu',Ayyappa:'Ayyappa / Sastha',Vaishno\u0020Devi:'Devi / Shakti'}[t.focus]||t.focus);t.aliases=t.aliases||[]});window.templeMapTemples=temples;
const normalize=s=>String(s??'').normalize('NFKC').toLocaleLowerCase().replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[\s\-–—'’.`]/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=r=>{state.previousRoute=state.route;location.hash=r};
const live=()=>{const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;let l='Live',x='';if(!navigator.onLine){l='No Data';x='no-data'}else if(c&&['slow-2g','2g'].includes(c.effectiveType)){l='Weak Data';x='weak-data'}return `<span class="connectivity ${x}"><i></i>${l}</span>`};
const head=(t,b='home')=>`<div class="page-head"><a class="back" href="#${esc(b)}">← Back</a><h1>${esc(t)}</h1></div>`;
const searchBox=(id,val='')=>`<div class="search-box"><input id="${id}" value="${esc(val)}" placeholder="Search in English or Malayalam" autocomplete="off"><button class="search-go" id="${id}Go">⌕</button></div>`;
const results=q=>{const n=normalize(q);return n?temples.filter(t=>[t.name,t.ml,t.place,t.district,t.state,t.focus,t.sacredFocus,t.type,t.tradition,...(t.aliases||[])].some(v=>normalize(v).includes(n))):[]};
const distance=t=>{if(!state.location)return 999999;const p=Math.PI/180,a=.5-Math.cos((t.lat-state.location.lat)*p)/2+Math.cos(state.location.lat*p)*Math.cos(t.lat*p)*(1-Math.cos((t.lng-state.location.lng)*p))/2;return 12742*Math.asin(Math.sqrt(a))};
const sortResults=a=>{a=[...a];return state.sort==='az'?a.sort((x,y)=>x.name.localeCompare(y.name)):state.sort==='za'?a.sort((x,y)=>y.name.localeCompare(x.name)):state.sort==='stateaz'?a.sort((x,y)=>x.state.localeCompare(y.state)||x.name.localeCompare(y.name)):state.sort==='stateza'?a.sort((x,y)=>y.state.localeCompare(x.state)||y.name.localeCompare(x.name)):state.sort==='near'?a.sort((x,y)=>distance(x)-distance(y)):state.sort==='far'?a.sort((x,y)=>distance(y)-distance(x)):a};
const link=t=>`<a class="result-link" href="#temple/${t.id}"><div class="result-thumb"></div><div class="result-main"><strong>${esc(t.name)}</strong><span>${esc(t.place)}, ${esc(t.district)}, ${esc(t.state)}</span><small>✦ ${esc(t.sacredFocus||t.focus)} · ${esc(t.type)}</small></div><b class="result-arrow">›</b></a>`;
function home(){const h=state.homeData||{},ids=h.featuredTempleIds||['ochira','kottakkal-vishwambhara','somnath','tirumala'],fs=ids.map(id=>temples.find(t=>t.id===id)).filter(Boolean),news=(h.newsLinks||[]).map(x=>`<a class="news-link" href="${esc(x.url)}" target="_blank" rel="noopener"><strong>${esc(x.title)}</strong><small>${esc(x.source||'Original source')}</small></a>`).join('');return `<section class="home-page"><div class="home-inner"><div class="hero-wallpaper"><div class="hero-copy"><div class="eyebrow">EXPLORE · DISCOVER · CONNECT</div><h1>TempleMap India</h1><p>India’s Sacred Places</p></div></div><div class="home-status">${live()}</div>${searchBox('homeSearch')}<div class="actions"><button class="primary" id="homeSearchButton">⌕ Search Temples</button><a class="secondary" href="#browse">☷ Browse</a></div><section class="section"><h2>Featured Temples</h2><div class="feature-strip">${fs.map(t=>`<a class="feature" href="#temple/${t.id}"><div class="feature-thumb"></div><strong>${esc(t.name)}</strong><small>${esc(t.place)}</small></a>`).join('')}</div></section><section class="section"><h2>Latest Temple News & Festivals</h2>${news?`<div class="news-list">${news}</div>`:'<div class="card"><strong>Updates will appear here</strong><small>Official and verified current links can be added through the data files.</small></div>'}</section></div></section>`}
function search(){const r=sortResults(results(state.query));return `${head('Search Temples')}${searchBox('searchInput',state.query)}${state.query?`<span class="count-pill">${r.length.toLocaleString()} results found</span>${r.length?`<div class="result-list search-page-list">${r.map(link).join('')}</div>`:'<div class="empty">No matching temples found.</div>'}`:'<p class="muted">Search by temple name, Malayalam name, place, district, state or sacred focus.</p>'}`}
function browse(){return `<section class="browse-page"><div class="browse-page-wrap">${head('Browse Temples')}<div class="browse-toolbar"><p class="browse-help">Choose filters, then view matching temples.</p><button class="secondary" id="sortButton">⇅ Sort</button></div><div class="browse-grid">${Object.entries(browseData).map(([n,o])=>`<label class="browse-row"><span><strong>${esc(n)}</strong><small>${o.length?o.length+' options':'From data index'}</small></span><select data-browse="${esc(n)}"><option value="">Select</option>${o.map(v=>`<option value="${esc(v)}" ${state.filters[n]===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`).join('')}</div><button class="primary view-button" id="viewBrowse">⌕ View Temples</button></div></section>`}
function sortPanel(){return `${head('Sort Temples','browse')}<div class="sort-panel card"><label>Sort Temples</label><select class="sort-select" id="sortSelect"><option value="relevance">Relevance (Default)</option><option value="az">Name (A → Z)</option><option value="za">Name (Z → A)</option><option value="near">Distance (Near → Far)</option><option value="far">Distance (Far → Near)</option><option value="stateaz">State (A → Z)</option><option value="stateza">State (Z → A)</option></select><button class="primary" id="applySort">Apply</button></div>`}
function filtered(){return sortResults(temples.filter(t=>Object.entries(state.filters).every(([k,v])=>!v||(k==='State / Union Territory'?t.state===v:k==='District'?t.district===v:k==='Village / Town / City'?t.place===v:k==='Sacred Focus'?t.sacredFocus===v:k==='Site Category'?t.type===v:k==='Sect / Tradition'?t.tradition===v:true))))}
function browseResults(){const r=filtered();return `${head('Browse Results','browse')}<span class="count-pill">${r.length} results found</span><div class="result-list">${r.length?r.map(link).join(''):'<div class="empty">No temples match the selected filters.</div>'}</div>`}
function favourites(){const s=temples.filter(t=>state.favourites.includes(t.id));return `<section class="favourites-page">${head('Favourites')}${s.length?`<div class="result-list favourite-list">${s.map(link).join('')}</div>`:'<div class="empty">No favourites saved yet.</div>'}</section>`}
function temple(id){const t=temples.find(x=>x.id===id);if(!t)return'<div class="empty">Temple not found.</div>';const saved=state.favourites.includes(id),u=state.templeUpdates?.temples?.[id]||{};return `<section class="detail-page">${head('Temple',state.previousRoute||'home')}<div class="detail-full"><div class="detail-image"></div><div class="detail-panel"><div class="temple-title"><div><h2>${esc(t.name)}</h2><p class="muted ml-text">${esc(t.ml)}</p></div><button class="icon-small" id="favButton">${saved?'♥':'♡'}</button></div><p class="place-line">📍 ${esc(t.place)}, ${esc(t.district)}, ${esc(t.state)}</p><div class="field"><b>Sacred Focus</b><span>${esc(t.sacredFocus||t.focus)}</span></div><div class="field"><b>Site Category</b><span>${esc(t.type)}</span></div><div class="field"><b>Traditional / Local Name</b><span>${esc(t.focus)}</span></div><div class="field"><b>Tradition</b><span>${esc(t.tradition)}</span></div><div class="actions compact"><button class="${saved?'secondary':'primary'}" id="favText">${saved?'♥ Saved':'♡ Add to Favourites'}</button><button class="secondary" id="shareTemple">↗ Share</button></div>${(u.links||[]).length?`<section class="section"><h3>Official Temple Links</h3><div class="actions">${u.links.map(x=>`<a class="secondary" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join('')}</div></section>`:''}<section class="section"><h3>${u.newsLinks?.length?'Latest News & Festivals':'Nearby Temples'}</h3><p class="muted">${u.newsLinks?.length?'Current links are supplied from the temple update data file.':'Nearby temples will appear when the India-wide location index is connected.'}</p></section><div class="notice">TempleMap India is an independent public information resource. Verify changing information with the original authority before travelling.</div></div></div></section>`}
function settings(){return `${head('Settings')}<div class="settings-list"><div class="card setting-row"><div><strong>📍 Location</strong><small id="locationState">${state.location?'Location enabled for this browser.':'Enable location for nearby-temple features.'}</small></div><button class="secondary" id="locationButton">${state.location?'Enabled':'Enable'}</button></div><div class="card setting-row"><div><strong>AA · Text Size</strong><small>Changes text size while keeping the frame and layout fixed.</small></div><select id="textSize"><option value="small" ${state.textSize==='small'?'selected':''}>Small</option><option value="normal" ${state.textSize==='normal'?'selected':''}>Normal</option><option value="large" ${state.textSize==='large'?'selected':''}>Large</option><option value="xlarge" ${state.textSize==='xlarge'?'selected':''}>Extra Large</option></select></div><div class="card"><strong>Share TempleMap India</strong><small>Share this independent public resource.</small><div class="actions compact"><button class="secondary" id="shareApp">↗ Share</button></div></div><div class="card"><strong>About</strong><small>TempleMap India is an independent public information directory, not a government website or government service.</small></div><div class="card"><strong>Privacy</strong><small>Favourites and text-size preference are stored locally in this browser.</small></div></div>`}
function render(){const app=document.getElementById('app'),[base,id]=state.route.split('/');app.innerHTML=base==='search'?search():base==='browse'?browse():base==='browse-results'?browseResults():base==='sort'?sortPanel():base==='favourites'?favourites():base==='temple'?temple(id):base==='settings'?settings():home();app.classList.toggle('tab-fixed',['home','browse','browse-results','settings','temple'].includes(base));document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===base||(base==='temple'&&state.previousRoute.split('/')[0]===a.dataset.nav)));document.body.dataset.textSize=state.textSize;bind()}
function runSearch(id){const e=document.getElementById(id);if(e){state.query=e.value.trim();nav('search')}}
function bind(){document.getElementById('settingsButton')?.addEventListener('click',()=>nav('settings'));document.getElementById('homeSearchButton')?.addEventListener('click',()=>runSearch('homeSearch'));document.getElementById('homeSearchGo')?.addEventListener('click',()=>runSearch('homeSearch'));document.getElementById('searchInputGo')?.addEventListener('click',()=>runSearch('searchInput'));['homeSearch','searchInput'].forEach(id=>document.getElementById(id)?.addEventListener('keydown',e=>{if(e.key==='Enter')runSearch(id)}));document.getElementById('sortButton')?.addEventListener('click',()=>nav('sort'));document.getElementById('viewBrowse')?.addEventListener('click',()=>nav('browse-results'));document.querySelectorAll('[data-browse]').forEach(s=>s.addEventListener('change',()=>{state.filters[s.dataset.browse]=s.value}));document.getElementById('applySort')?.addEventListener('click',()=>{state.sort=document.getElementById('sortSelect').value;nav('browse-results')});document.getElementById('textSize')?.addEventListener('change',e=>{state.textSize=e.target.value;localStorage.setItem('templemap-text-size',state.textSize);document.body.dataset.textSize=state.textSize});document.getElementById('locationButton')?.addEventListener('click',()=>{if(!navigator.geolocation){document.getElementById('locationState').textContent='Location is not supported by this browser.';return}navigator.geolocation.getCurrentPosition(p=>{state.location={lat:p.coords.latitude,lng:p.coords.longitude};document.getElementById('locationState').textContent='Location enabled for this browser.';document.getElementById('locationButton').textContent='Enabled'},()=>{document.getElementById('locationState').textContent='Location permission was denied or unavailable.'})});document.getElementById('favButton')?.addEventListener('click',toggleFav);document.getElementById('favText')?.addEventListener('click',toggleFav);document.getElementById('shareTemple')?.addEventListener('click',()=>share(location.href));document.getElementById('shareApp')?.addEventListener('click',()=>share(location.href))}
function toggleFav(){const id=state.route.split('/')[1];state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];localStorage.setItem('templemap-favourites',JSON.stringify(state.favourites));render()}
async function share(url){if(navigator.share)try{await navigator.share({title:'TempleMap India',url})}catch{}else if(navigator.clipboard)await navigator.clipboard.writeText(url)}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'home';render()});
fetch('data/home-data.json').then(r=>r.ok?r.json():{}).then(x=>{state.homeData=x;render()}).catch(()=>render());fetch('data/temple-updates.json').then(r=>r.ok?r.json():{}).then(x=>{state.templeUpdates=x;render()}).catch(()=>{});render();
