const state={route:location.hash.replace('#','')||'home',previousRoute:'home',query:'',favourites:JSON.parse(localStorage.getItem('templemap-favourites')||'[]'),textSize:localStorage.getItem('templemap-text-size')||'normal',homeData:null,templeUpdates:null,connection:'Live'};
const temples=[
{id:'ochira',name:'Oachira Parabrahma Temple',ml:'ഓച്ചിറ പരബ്രഹ്മ ക്ഷേത്രം',place:'Oachira',district:'Kollam',state:'Kerala',focus:'Parabrahmam',type:'Pilgrimage centre',tradition:'Non-idol worship'},
{id:'kottakkal-vishwambhara',name:'Kottakkal Vishwambhara Temple',ml:'കോട്ടക്കൽ വിശ്വംഭര ക്ഷേത്രം',place:'Kottakkal',district:'Malappuram',state:'Kerala',focus:'Shiva',type:'Temple',tradition:'Hindu'},
{id:'somnath',name:'Somnath Temple',ml:'സോമനാഥ ക്ഷേത്രം',place:'Prabhas Patan',district:'Gir Somnath',state:'Gujarat',focus:'Shiva',type:'Temple',tradition:'Hindu'},
{id:'vaishno-devi',name:'Shri Mata Vaishno Devi Shrine',ml:'ശ്രീ മാതാ വൈഷ്ണോ ദേവി ക്ഷേത്രം',place:'Katra',district:'Reasi',state:'Jammu and Kashmir',focus:'Vaishno Devi',type:'Shrine',tradition:'Hindu'},
{id:'tirumala',name:'Tirumala Venkateswara Temple',ml:'തിരുമല വെങ്കടേശ്വര ക്ഷേത്രം',place:'Tirumala',district:'Tirupati',state:'Andhra Pradesh',focus:'Venkateswara',type:'Temple',tradition:'Vaishnavism'},
{id:'sabarimala',name:'Sabarimala Sree Dharma Sastha Temple',ml:'ശബരിമല ശ്രീ ധർമ്മശാസ്താ ക്ഷേത്രം',place:'Sabarimala',district:'Pathanamthitta',state:'Kerala',focus:'Ayyappa',type:'Temple',tradition:'Hindu'},
{id:'guruvayur',name:'Guruvayur Sree Krishna Temple',ml:'ഗുരുവായൂർ ശ്രീകൃഷ്ണ ക്ഷേത്രം',place:'Guruvayur',district:'Thrissur',state:'Kerala',focus:'Krishna',type:'Temple',tradition:'Vaishnavism'},
{id:'kashi-vishwanath',name:'Kashi Vishwanath Temple',ml:'കാശി വിശ്വനാഥ ക്ഷേത്രം',place:'Varanasi',district:'Varanasi',state:'Uttar Pradesh',focus:'Shiva',type:'Temple',tradition:'Hindu'}];
const browseData={'State / Union Territory':['Kerala','Gujarat','Andhra Pradesh','Jammu and Kashmir','Uttar Pradesh'],'Religion':['Hindu','Buddhist','Jain','Sikh','Other'],'Sect / Tradition':['Vaishnavism','Shaivism','Non-idol worship'],'Deity / Sacred Focus':['Shiva','Venkateswara','Vaishno Devi','Ayyappa','Krishna','Parabrahmam'],'Site Category':['Temple','Shrine','Pilgrimage centre'],'Heritage':['Heritage site','ASI protected','Other heritage'],'Historical Figure':['Historical figure'],'Architecture':['Dravidian','Nagara','Vesara','Regional'],'Pilgrimage / Temple Circuits':['Char Dham','Jyotirlinga','Shakti Peetha','Regional circuit']};
const normalize=v=>String(v||'').normalize('NFC').toLocaleLowerCase().replace(/[\u200c\u200d\uFEFF]/g,'').replace(/[\s\-–—'’.]/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveFav(){localStorage.setItem('templemap-favourites',JSON.stringify(state.favourites));}
function applyText(){document.body.classList.remove('small-text','large-text','xlarge-text');if(state.textSize==='small')document.body.classList.add('small-text');if(state.textSize==='large')document.body.classList.add('large-text');if(state.textSize==='xlarge')document.body.classList.add('xlarge-text');}
function go(route){location.hash=route;}
function searchTemples(q){const n=normalize(q);return n?temples.filter(t=>[t.name,t.ml,t.place,t.district,t.state,t.focus,t.type,t.tradition].some(v=>normalize(v).includes(n))):[];}
function searchBar(id,value=''){return `<div class="search-box"><input id="${id}" value="${esc(value)}" placeholder="Search in English or Malayalam" autocomplete="off" enterkeyhint="search"><button class="search-go" id="${id}Go" aria-label="Search">⌕</button></div>`;}
function backButton(target){return `<a class="back-glass" href="#${target||'home'}">← <span>Back</span></a>`;}
function thumb(){return `<img src="assets/temple-thumb.svg" alt="Indian temple illustration" loading="lazy">`;}
function resultLink(t){return `<a class="result-link" href="#temple/${t.id}"><div class="result-thumb">${thumb()}</div><div><strong>${esc(t.name)}</strong><span class="muted">${esc(t.place)}, ${esc(t.district)}, ${esc(t.state)}</span><small>${esc(t.focus)} · ${esc(t.type)}</small></div><b class="result-arrow">›</b></a>`;}
function pageHead(title,target='home'){return `<div class="page-head">${backButton(target)}<h1>${title}</h1></div>`;}
function searchPage(){const r=searchTemples(state.query);return `${pageHead('Search','home')}${searchBar('searchInput',state.query)}${state.query?`<span class="count-pill">${r.length.toLocaleString()} results found</span>`:'<p class="muted">Search by temple name, place, district, state, deity or sacred focus.</p>'}${r.length?`<div class="result-list search-page-list">${r.map(resultLink).join('')}</div>`:state.query?'<div class="empty">No matching temples found.</div>':''}`;}
function homePage(){const h=state.homeData||{},featured=(h.featuredTempleIds||['ochira','kottakkal-vishwambhara','somnath','tirumala']).map(id=>temples.find(t=>t.id===id)).filter(Boolean),news=(h.newsLinks||[]);return `<section class="home-intro"><div><div class="eyebrow">Explore · Discover · Connect</div><h1>India’s Sacred Places</h1><p>${esc(h.description||'A lightweight directory of temples and sacred places across India.')}</p></div>${statusPill()}</section>${searchBar('homeSearch')}<div class="home-actions"><a class="primary" href="#search">⌕ <span>Search Temples</span></a><a class="secondary" href="#browse">▦ <span>Browse by Category</span></a></div><section class="section"><div class="section-title"><h2>Featured Temples</h2><a href="#browse">See all</a></div><div class="feature-strip">${featured.map(t=>`<a class="feature" href="#temple/${t.id}"><div class="feature-thumb">${thumb()}</div><strong>${esc(t.name)}</strong><small>${esc(t.place)}</small></a>`).join('')}</div></section><section class="section"><div class="section-title"><h2>Latest Temple News & Festivals</h2></div>${news.length?`<div class="news-list">${news.map(x=>`<a href="${esc(x.url)}" target="_blank" rel="noopener"><strong>${esc(x.title)}</strong><small>${esc(x.source||'Original source')}</small></a>`).join('')}</div>`:'<div class="card"><strong>Updates will appear here</strong><small>Official and verified current links can be added through data/updates.json.</small></div>'}</section>`;}
function statusPill(){const cls=state.connection.toLowerCase().replace(' ','-');return `<div class="status-pill ${cls}" title="Informational data/connection status"><i></i><span>${state.connection}</span></div>`;}
function browsePage(){return `${pageHead('Browse','home')}<p class="muted">Select a classification. These values are ready for connection to the full India-wide data index.</p><div class="filter-list">${Object.entries(browseData).map(([n,o])=>`<label class="filter-row"><span><strong>${esc(n)}</strong><small>Full India index</small></span><select data-browse="${esc(n)}"><option value="">Select</option>${o.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`).join('')}</div>`;}
function favouritesPage(){const saved=temples.filter(t=>state.favourites.includes(t.id));return `${pageHead('Favourites','home')}${saved.length?`<div class="result-list favourite-list">${saved.map(resultLink).join('')}</div>`:'<div class="empty">No favourites saved yet.<br>Open a temple and choose “Add to Favourites”.</div>'}`;}
function templePage(id){const t=temples.find(x=>x.id===id);if(!t)return'<div class="empty">Temple not found.</div>';const saved=state.favourites.includes(t.id),u=state.templeUpdates?.temples?.[t.id]||{},links=(u.links||[]).map(x=>`<a class="secondary" href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.label)}</a>`).join(''),news=(u.newsLinks||[]).map(x=>`<a class="result-link compact" href="${esc(x.url)}" target="_blank" rel="noopener"><div><strong>${esc(x.title)}</strong><small>${esc(x.source||'Original source')}</small></div></a>`).join('');return `${pageHead('Temple',state.previousRoute||'search')}<div class="temple-top"><div class="detail-image">${thumb()}</div><div class="detail-panel detail-scroll"><div class="temple-title-row"><div><h2>${esc(t.name)}</h2><p class="muted">${esc(t.ml)}</p></div><button class="icon-small" id="favButton" aria-label="Favourite">${saved?'♥':'♡'}</button></div><p class="place-line">📍 ${esc(t.place)}, ${esc(t.district)}, ${esc(t.state)}</p><div class="field"><b>Sacred Focus</b>${esc(t.focus)}</div><div class="field"><b>Site Category</b>${esc(t.type)}</div><div class="field"><b>Tradition</b>${esc(t.tradition)}</div><div class="actions"><button class="${saved?'secondary':'primary'}" id="favText">${saved?'♥ Saved':'♡ Add to Favourites'}</button><button class="secondary" id="shareTemple">↗ Share</button></div>${links?`<section class="section"><h3>Official Temple Links</h3><div class="actions">${links}</div></section>`:''}${news?`<section class="section"><h3>Latest News & Festivals</h3><div class="result-list">${news}</div></section>`:'<section class="section"><h3>Nearby Temples</h3><p class="muted">Nearby temples will be generated automatically from the full India data index.</p></section>'}<div class="notice">TempleMap India is an independent public information resource. Verify changing information with the original authority before travelling.${u.lastVerified?` Last verified: ${esc(u.lastVerified)}.`:''}</div></div></div>`;}
function settingsPage(){return `${pageHead('Settings','home')}<div class="settings-list"><div class="card setting-card"><div><strong>📍 Location Access</strong><small id="locationState">Enable location to show nearby temples on the map.</small></div><button class="secondary" id="locationButton">Enable</button></div><div class="card setting-card"><div><strong>AA &nbsp; Text Size</strong><small>Choose a size that reflows the layout.</small></div><select id="textSize"><option value="small" ${state.textSize==='small'?'selected':''}>Small</option><option value="normal" ${state.textSize==='normal'?'selected':''}>Normal</option><option value="large" ${state.textSize==='large'?'selected':''}>Large</option><option value="xlarge" ${state.textSize==='xlarge'?'selected':''}>Extra Large</option></select></div><div class="card"><strong>Share TempleMap India</strong><small>Share this public resource with friends.</small><div class="share-list"><button class="secondary" id="shareApp">↗ Share</button><a class="secondary" target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(location.href)}">Facebook</a><a class="secondary" target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?url=${encodeURIComponent(location.href)}&text=TempleMap%20India">X</a></div></div><div class="card"><strong>About</strong><small>TempleMap India is an independent public information directory, not a government website or government service.</small></div><div class="card"><strong>Privacy</strong><small>Favourites and text-size preference are stored locally in this browser.</small></div></div>`;}
async function loadData(){for(const [key,file] of [['homeData','home-data.json'],['templeUpdates','temple-updates.json']]){try{state[key]=await fetch(`data/${file}`).then(r=>r.ok?r.json():null)}catch(e){}}updateConnection();render();}
function updateConnection(){if(!navigator.onLine){state.connection='No Data';return;}state.connection='Live';fetch('data/home-data.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw 0;state.connection='Live';}).catch(()=>state.connection='Weak Data');}
function updateNav(base){document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===base||(base==='temple'&&state.previousRoute.split('/')[0]===a.dataset.nav)));}
function render(){const app=document.getElementById('app'),[base,id]=state.route.split('/');app.innerHTML=base==='temple'?templePage(id):base==='search'?searchPage():base==='browse'?browsePage():base==='favourites'?favouritesPage():base==='settings'?settingsPage():homePage();app.classList.toggle('tab-fixed',!['search','favourites'].includes(base));document.getElementById('settingsButton').hidden=base!=='home';updateNav(base);bind();applyText();app.scrollTop=0;}
function runSearch(id){const e=document.getElementById(id);if(e){state.query=e.value.trim();go('search');}}
function bind(){document.getElementById('homeSearchGo')?.addEventListener('click',()=>runSearch('homeSearch'));document.getElementById('searchInputGo')?.addEventListener('click',()=>runSearch('searchInput'));document.getElementById('homeSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')runSearch('homeSearch')});document.getElementById('searchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')runSearch('searchInput')});document.getElementById('settingsButton')?.addEventListener('click',()=>go('settings'));document.getElementById('locationButton')?.addEventListener('click',()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(()=>{document.getElementById('locationState').textContent='Location access is enabled on this device.'},()=>{document.getElementById('locationState').textContent='Location permission was not granted.'}):document.getElementById('locationState').textContent='Geolocation is not supported by this browser.');document.getElementById('textSize')?.addEventListener('change',e=>{state.textSize=e.target.value;localStorage.setItem('templemap-text-size',state.textSize);applyText()});const fav=()=>{const id=state.route.split('/')[1];state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];saveFav();render()};document.getElementById('favButton')?.addEventListener('click',fav);document.getElementById('favText')?.addEventListener('click',fav);document.getElementById('shareTemple')?.addEventListener('click',()=>share(location.href,'TempleMap India'));document.getElementById('shareApp')?.addEventListener('click',()=>share(location.href,'TempleMap India'));}
async function share(url,title){if(navigator.share){try{await navigator.share({title,url})}catch(e){}}else if(navigator.clipboard){await navigator.clipboard.writeText(url);alert('Link copied.')}}
window.addEventListener('hashchange',()=>{const next=location.hash.replace('#','')||'home';if(next.startsWith('temple/')&&state.route!==next)state.previousRoute=state.route;state.route=next;render()});window.addEventListener('online',()=>{state.connection='Live';if(state.route==='home')render()});window.addEventListener('offline',()=>{state.connection='No Data';if(state.route==='home')render()});loadData();
